### ISSUE TITLE
aria_chk is rotten

### ISSUE THREAD

**Issue by musicpanda** [MariaDB/mariadb.org-tools#116]
Using MariaDb with Xampp my MariaDB wouldn't start anymore after a Windows update. I got the error:

`2022-02-01 12:24:57 0 [ERROR] mysqld.exe: Aria recovery failed. Please run aria_chk -r on all Aria tables and delete all aria_log.######## files
2022-02-01 12:24:57 0 [ERROR] Plugin 'Aria' init function returned error.
2022-02-01 12:24:57 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.`

Running aria_chk -r I saw a lot of messages that tables have been resized from 0 to something else. For example 
`mysql.columns_priv
warning  : Number of rows changed from 0 to 29
status   : OK`
The size of those tabes was reduced.

After that nothing worked. After some manipulations I could open Phpmyadmin and see the tables. But I couldn't see their content or manipulate them.

As it is now I believe that aria_chk might better be described as aria_destroy...

**Comment by grooverdan** [comment]
There are a couple of [aria_chk bugs](https://jira.mariadb.org/issues/?jql=text%20~%20%22aria_chk%22%20and%20status!%3DClosed) in progress. More detail like the error code, MariaDB version(s), Windows Version would assist in determining if this is a new bug or and existing one. If you have those details can you examine the existing bug reports, and create a new bug report if this isn't the same.
