### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by celestinoxp** [MariaDB/mariadb.org-tools#126]
Hi,

i don't know if this place is right place to post this.

In ci.maradb.org there are several builds centos, rhel, linux, etc.. but for windows it doesn't show anything. Can you check this?

**Comment by grooverdan** [comment]
ci contains the build artifacts for internal builds between buildbot steps.

The Windows builder is https://buildbot.mariadb.org/#/builders/amd64-windows
