### ISSUE TITLE
Are issues created on your JIRA deletable?

### ISSUE THREAD

**Issue by flowl** [MariaDB/mariadb.org-tools#53]
When opening a bug ticket at https://jira.mariadb.org/browse/
are we able to delete what we created?
Is your bugtracker fully GDPR compliant?

I had many problems especially with JIRA and Trac that they claim GDPR compliancy when they are actually not.

**Comment by an3l** [comment]
Maybe @rasmushoj may help with this?

**Comment by grooverdan** [comment]
At the moment there is no self delete option on MDEVs. I have found the option exists on other internal project there. I'm asking around to see if its an exposable feature (will be under the "More" section of a issue).

I have been able to ask an admin remove tickets where license credentials where inadvertently included.

What exactly is the GDPR requirement that needs to be implemented? In what way does JIRA fail on this?

**Comment by flowl** [comment]
Hi @grooverdan and first of all, thanks for taking care of this!

When I give lose information into a system (by "lose information" I'm talking about information that isn't part of a financial transaction or part of a contract that has higher precedence than GDPR itself), personal information (my nickname, probably my email and real name, my account information) is appended to the bug report. I need to be able to delete the personal information.

Concerning GDPR it's probably ok if there is not an automated way to get the information deleted, but it needs to be clear that I can request my data to be deleted at any time.

In the past, I have reported things to Wordpress and they are not letting authors delete their personal information and now denying my GDPR request.
I have filed GDPR complaints at the responsible data privacy agency (now in multiple countries) but Wordpress does ignore it.

I don't want to be in that situation ever again.

If you give me the option to put information into your system (like a bug report), you must give me the option to delete the same information without any barriers.

Otherwise, I'm not reporting any bugs.

**Comment by iangilfillan** [comment]
JIRA seems to have done a lot of work on GDPR-compliance including support for user anonymization - see https://confluence.atlassian.com/jiracore/gdpr-anonymizing-users-983503046.html. Unfortunately the current MariaDB instance is older and doesn't seem to support this, so will first need to be upgraded.

**Comment by flowl** [comment]
@iangilfillan This is actually awesome, as it also includes mentions in comments! This is gonna be restoring trust in JIRA.

**Comment by flowl** [comment]
I just discovered that in JetBrains YouTrack, administrators have the ability to restore deleted contents.
Is it the same disaster for Jira?
It's anti-dataprivacy. The opposite of what all the compliancy and regulations aim for.

**Comment by iangilfillan** [comment]
We don't yet have a new version of JIRA running to see for sure, so I suggest asking this to Atlassian in the meantime.

**Comment by grooverdan** [comment]
Jira Server (http://jira.mariadb.org/) has been upgraded to 8.13.13. This is an LTS release that includes the GDPR anonymization.
